
version: "3.6"
services:
  front:
    image: node:latest
    working_dir: "/var/www/app"
    environment:
      - HOST=0.0.0.0
    ports:
      - "80:3000"
    volumes:
      - .:/var/www/app
    command: bash -c "npm install && npm run dev"
